### ISSUE TITLE
Carthage build fails on ExampleModel in v6.0

### ISSUE THREAD

**Issue by darkhonor** [jessesquires/JSQCoreDataKit#100]
## New issue checklist

- [x] I have read the [`README`](https://github.com/jessesquires/JSQCoreDataKit/blob/develop/README.md) and [docs](http://www.jessesquires.com/JSQCoreDataKit/).
- [x] I have reviewed the [contributing guidelines](https://github.com/jessesquires/HowToContribute).
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQCoreDataKit/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- Library version(s): 6.0
- OS version(s): macOS Sierra
- Devices/Simulators affected: All
- Reproducible in the demo project (Yes/No): Yes 
- Related issues: N/A

## Expected behavior
Successfully build using: $ carthage update

## Actual behavior
Build fails when building scheme "ExampleModel-OSX"

## Steps to reproduce
Run $ carthage update

### Crash log? Screenshots? Videos? Sample project?
aackerman$ carthage update
*** Fetching JSQCoreDataKit
*** Checking out JSQCoreDataKit at "6.0.0"
*** xcodebuild output can be found in /var/folders/6j/0bvnfctj4sx583zk7wg6ds_h0000gn/T/carthage-xcodebuild.qpDJ8s.log
*** Building scheme "JSQCoreDataKit-OSX" in JSQCoreDataKit.xcodeproj
*** Building scheme "JSQCoreDataKit-iOS" in JSQCoreDataKit.xcodeproj
*** Building scheme "JSQCoreDataKit-tvOS" in JSQCoreDataKit.xcodeproj
*** Building scheme "JSQCoreDataKit-watchOS" in JSQCoreDataKit.xcodeproj
*** Building scheme "ExampleModel-OSX" in ExampleModel.xcodeproj
** BUILD FAILED **

The following build commands failed:
	CompileSwift normal x86_64 /Users/aackerman/Developer/VTModel/Carthage/Checkouts/JSQCoreDataKit/Example/ExampleModel/ExampleModel/Model.swift
	CompileSwift normal x86_64 /Users/aackerman/Developer/VTModel/Carthage/Checkouts/JSQCoreDataKit/Example/ExampleModel/ExampleModel/Company.swift
	CompileSwift normal x86_64 /Users/aackerman/Developer/VTModel/Carthage/Checkouts/JSQCoreDataKit/Example/ExampleModel/ExampleModel/Employee.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(4 failures)
/Users/aackerman/Developer/VTModel/Carthage/Checkouts/JSQCoreDataKit/Example/ExampleModel/ExampleModel/Company.swift:21:8: error: no such module 'JSQCoreDataKit'
/Users/aackerman/Developer/VTModel/Carthage/Checkouts/JSQCoreDataKit/Example/ExampleModel/ExampleModel/Company.swift:21:8: error: no such module 'JSQCoreDataKit'
/Users/aackerman/Developer/VTModel/Carthage/Checkouts/JSQCoreDataKit/Example/ExampleModel/ExampleModel/Company.swift:21:8: error: no such module 'JSQCoreDataKit'
A shell task (/usr/bin/xcrun xcodebuild -project /Users/aackerman/Developer/VTModel/Carthage/Checkouts/JSQCoreDataKit/Example/ExampleModel/ExampleModel.xcodeproj -scheme ExampleModel-OSX -configuration Release ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **

The following build commands failed:
	CompileSwift normal x86_64 /Users/aackerman/Developer/VTModel/Carthage/Checkouts/JSQCoreDataKit/Example/ExampleModel/ExampleModel/Model.swift
	CompileSwift normal x86_64 /Users/aackerman/Developer/VTModel/Carthage/Checkouts/JSQCoreDataKit/Example/ExampleModel/ExampleModel/Company.swift
	CompileSwift normal x86_64 /Users/aackerman/Developer/VTModel/Carthage/Checkouts/JSQCoreDataKit/Example/ExampleModel/ExampleModel/Employee.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(4 failures)

**Comment by darkhonor** [comment]
I have verified once I open the Checked-out project in Xcode directly, both the ExampleModel and main projects build/test with no problems.

**Comment by jessesquires** [comment]
Thanks @darkhonor ! 👍 

I won't have much time to look into this. Will accept a PR though! 😄

**Comment by jessesquires** [comment]
@darkhonor - just tagged and released 6.0.1 😄

**Comment by darkhonor** [comment]
Awesome!  Thank you @jessesquires and @tonyarnold
