### ISSUE TITLE
Destroying persistent store with iOS 9 NSPersistentStoreCoordinator method.

### ISSUE THREAD

**Issue by DenHeadless** [jessesquires/JSQCoreDataKit#104]
## New issue checklist

- [x] I have read the [`README`](https://github.com/jessesquires/JSQCoreDataKit/blob/develop/README.md) and [docs](http://www.jessesquires.com/JSQCoreDataKit/).
- [x] I have reviewed the [contributing guidelines](https://github.com/jessesquires/HowToContribute).
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQCoreDataKit/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- Library version(s): 6.0.1

As of iOS 9 Apple provides `destroyPersistentStore(at:ofType:options:)` method for `NSPersistentStoreCoordinator`.  Would you consider conditionally replacing following methods(https://github.com/jessesquires/JSQCoreDataKit/blob/develop/Source/CoreDataStack.swift#L166-L167) with the new one? 

Something like

```swift
if #available(iOS 9, tvOS 9, *) {
    try model.removeExistingStore()
    try storeCoordinator.remove(store)
} else {
    try storeCoordinator.destroyPersistentStore(...)
}
```

**Comment by jessesquires** [comment]
Thanks @DenHeadless ! 👍 

Sounds good to me 😊

**Comment by jessesquires** [comment]
However, I think you have your `if` and `else` mixed up 😄

**Comment by DenHeadless** [comment]
Ouch, sorry =) I'll try to make PR tomorrow =)
