### ISSUE TITLE
Crash when resetting in-memory core data stack

### ISSUE THREAD

**Issue by tomaskraina** [jessesquires/JSQCoreDataKit#123]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/jessesquires/JSQDataSourcesKit/blob/develop/README.md) and [documentation](http://www.jessesquires.com/JSQDataSourcesKit/).
- [x] I have reviewed the [contributing guidelines](https://github.com/jessesquires/HowToContribute).
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQDataSourcesKit/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- Library version: 6.0.3
- OS version: 11.2.5
- Devices/Simulators: devices
- Reproducible in the demo project (Yes/No): no
- Any related issues: no

## What happened?

When resetting in-memory core data stack, my app sometimes crashes on line where the main NSManagedObjectContext is being reset.

The crash message itself is something that Google doesn't find any results for:

```
Fatal Exception: NSInvalidArgumentException
Can't get value for 'batch' in bindings { }.
```

Whole crashlog can be found here: http://crashes.to/s/0def9cfcca4

My setup includes two CoreData stacks, one backed by SQLite database, the second in-memory only.

I'm using the following code to reset both stacks when a user logs out, for example.

```
    /**
     Asynchronously resets CD stacks and posts `DataRepositoryDidResetCoreDataNotification`
     */
    static public func resetCoreDataStack(completion: @escaping (StackResult) -> Void) {
        
        Log("Resetting Core Data stack ...")
        
        let startTime = CFAbsoluteTimeGetCurrent()
        SharedCoreDataStack.reset() { result in
            
            if let error = result.error() {
                LogError(error)
                fatalError(error.description)
            }
            
            SharedCoreDataInMemoryStack.reset() { memoryResult in
            
                Log("Done. Remove persistent store in \(formatedTimeIntervalSince(startTime)).")
                
                if let error = memoryResult.error() {
                    LogError(error)
                    fatalError(error.description)
                }
                
                NotificationCenter.default.post(
                    name: Notification.Name.DataRepository.DidResetCoreData,
                    object: nil,
                    userInfo: nil
                )
                
                completion(result)
            }
        }
    }
```

**Comment by jessesquires** [comment]
Thanks @tomaskraina !

Hard to say what's wrong without more info / steps to reproduce. 😊

**Comment by tomaskraina** [comment]
Once I know more about what the conditions are triggering this crash to happen I'll update this issue.

So far I haven't managed to reproduce it by myself. I only have the crash log. Luckily, this doesn't happen too often. Most probably, it's not even a bug in JSQCoreDataKit. I just wanted to have it documented somewhere so I can reference it in the future.

**Comment by tomaskraina** [comment]
I found out what was causing the crash, probably a bug in NSFetchedResultsController more info here: https://stackoverflow.com/questions/49052482/coredata-crash-cant-get-value-for-batch-in-bindings-when-resetting-nsm

**Comment by jessesquires** [comment]
Thanks 🙏 @tomaskraina!
