### ISSUE TITLE
Carthage builds ExampleModel.framework

### ISSUE THREAD

**Issue by alexcurylo** [jessesquires/JSQCoreDataKit#13]
Since Example.xcodeproj and JSQCoreDataKit.xcodeproj are at the same level, Carthage builds ExampleModel.framework which is undesired. Moving /Example into /JSQCoreDataKit seems to me to be the best way to resolve this if you have no objections.

**Comment by jessesquires** [comment]
thanks @alexcurylo !

**Comment by jessesquires** [comment]
hey @alexcurylo - actually, i just tried this and carthage **did not** build `ExampleModel`.

Running from the root directory:
````bash
$ carthage build --no-skip-current
*** xcodebuild output can be found in /var/folders/tx/s__fjnns3yd_23813_gwk7sh0000gn/T/carthage-xcodebuild.LwNg08.log
*** Building scheme "JSQCoreDataKit" in JSQCoreDataKit.xcworkspace
````

Then:
````bash
$ tree
├── Carthage
│   └── Build
│       └── iOS
│           └── JSQCoreDataKit.framework
│               ├── Headers
│               │   ├── JSQCoreDataKit-Swift.h
│               │   └── JSQCoreDataKit.h
│               ├── Info.plist
│               ├── JSQCoreDataKit
│               ├── Modules
│               │   ├── JSQCoreDataKit.swiftmodule
│               │   │   ├── arm.swiftdoc
│               │   │   ├── arm.swiftmodule
│               │   │   ├── arm64.swiftdoc
│               │   │   ├── arm64.swiftmodule
│               │   │   ├── i386.swiftdoc
│               │   │   ├── i386.swiftmodule
│               │   │   ├── x86_64.swiftdoc
│               │   │   └── x86_64.swiftmodule
│               │   └── module.modulemap
│               └── _CodeSignature
│                   └── CodeResources
````

**Comment by jessesquires** [comment]
And, running `carthage update` with the following `Cartfile` produces the same results:

````bash
github "jessesquires/JSQCoreDataKit"
````

Can you provide steps on how to reproduce your issue?

**Comment by alexcurylo** [comment]
Sure: [here's a cartfile](https://github.com/alexcurylo/swift-pose-gallery/blob/feature/Xcode_6_3/PoseGallery/Cartfile) on a shell project demonstrating the problem.

**Comment by jessesquires** [comment]
Well, we're clearly getting different results. :smile: 

I recently did a bit of refactoring regarding the project setup/organization. There is no longer an `ExampleModel` scheme in the workspace. So I think this is a caching problem.

Trying clearing `DerivedData/` and the carthage cache, and everything should be working.

**Comment by alexcurylo** [comment]
Yup, cleared out everything Carthage-related and it rebuilt fine. Sorry to bother you!

**Comment by jessesquires** [comment]
No worries! :smile:
