### ISSUE TITLE
Example target does not build

### ISSUE THREAD

**Issue by gsimmons** [jessesquires/JSQCoreDataKit#15]
ld: file not found: /Users/glensimmons/Library/Developer/Xcode/DerivedData/JSQCoreDataKit-gtnoirqkhjsldddhczuizwdxwvee/Build/Products/Debug-iphonesimulator/Example.app/Example
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by jessesquires** [comment]
hey @gsimmons - things are building fine for me. try cleaning all build targets, removing derived data, and restarting Xcode.

**Comment by gsimmons** [comment]
Still the same. Clean, Clean build folder, manually deleted DerivedData, restarted Xcode.

I’m using Xcode 6.3.2, btw.

**Comment by gsimmons** [comment]
Not sure why this is closed. The Example target doesn't build. My colleague had the same error.

**Comment by jessesquires** [comment]
hey @gsimmons - sorry about that. now fixed :smile:
