### ISSUE TITLE
Add persistent store to coordinator on background queue

### ISSUE THREAD

**Issue by bartcone** [jessesquires/JSQCoreDataKit#24]
Hey Jesse - was looking over the release-2.0 branch and noticed that the persistent store wasn't being added to the psc on a background thread. According to the new (preliminary) docs, they suggest you do so because it can take an unknown amount of time. Just thought I'd throw it out there.

> As part of the initialization of Core Data, assign the adding of the persistent store (NSPersistentStore) to the persistent store coordinator (NSPersistentStoreCoordinator) to a background queue. That action can take an unknown amount of time, and performing it on the main queue can block the user interface, possibly causing the application to terminate.

https://developer.apple.com/library/prerelease/ios/documentation/Cocoa/Conceptual/CoreData/IntegratingCoreData.html#//apple_ref/doc/uid/TP40001075-CH9-SW1

And there sample implementation fwiw.

```obj-c
dispatch_async(dispatch_get_global_queue( DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^(void) {
        NSError *error = nil;
        NSPersistentStoreCoordinator *psc = [[self managedObjectContext] persistentStoreCoordinator];
        NSPersistentStore *store = [psc addPersistentStoreWithType:NSSQLiteStoreType configuration:nil URL:storeURL options:options error:&error];
        NSAssert(store != nil, @"Error initializing PSC: %@\n%@", [error localizedDescription], [error userInfo]);
});
```
https://developer.apple.com/library/prerelease/ios/documentation/Cocoa/Conceptual/CoreData/InitializingtheCoreDataStack.html#//apple_ref/doc/uid/TP40001075-CH4-SW1

**Comment by jessesquires** [comment]
awesome. thanks @bartcone !

**Comment by tonyarnold** [comment]
How should this look? I'm happy to take a swing at implementing the feature, but given that nothing works without the PSC, we'll be returning an initialised instance of CoreDataStack that's not ready to use.

I guess we could add a protocol or a `viewDidLoad` analogue, but it feels a bit messy. Thanks, Core Data :trollface:

**Comment by bartcone** [comment]
I have something like this:

```swift
public typealias CallBack = Void -> Void    
public init(withStoreType storeType: String = NSSQLiteStoreType, callback: CallBack)
```   

```swift
let dataController = SomeController(withStoreType: NSSQLiteStoreType) {
    print("Stack initialized...do whatever")
}
```

**Comment by jessesquires** [comment]
Hey @tonyarnold / @bartcone — I've been thinking about this more, lately. I agree that this is awkward and presents an interesting challenge. 

1. We shouldn't be returning an object that is not fully initialized. This breaks Swift's expectations and guarantees regarding initialization. 
2. Dispatching work to a background queue and providing a completion callback for an initializer is not paradigmatic in Cocoa/Swift/Objective-C.
3. Doing either (1) or (2) seems like it would produce unintended side-effects/behaviors.
4. Initializers should be simple and only construction an object.
5. The `CoreDataStack` shouldn't be smart enough to know anything about threading.
6. We should avoid building any assumptions into `CoreDataStack` regarding threads.

Right now, I think the best scenario would be to initialize your whole stack on a background queue. It's not like you could use anything before it is initialized anyway. And, it seems risky to build-in these kind of assumptions. I think it is best and more flexible to leave this up to the client (when/where/how to init the stack).

**Proposed Solution:**
1. Leave `CoreDataStack` as-is. 
2. Update docs to specify that you should initialize your stack on a background queue.
3. *Maybe* provide a new external object to encapsulate the proper initialization flow? Maybe a `CoreDataStackFactory` or something, which would init the stack on a background queue, and return it on the main queue.

Any thoughts?

**Comment by bartcone** [comment]
I agree with 1 and 2. My example above was modeled after [Apple's sample code]
(https://developer.apple.com/library/prerelease/ios/documentation/Cocoa/Conceptual/CoreData/IntegratingCoreData.html#//apple_ref/doc/uid/TP40001075-CH9-SW1), but it's really senseless to have that callback.

If we went with 2, `Update docs to specify that you should initialize your stack on a background queue`, we may want to also point out that the default concurrency type is MainQueue. I'm not sure if that would cause any issues off the top of my head, but something worth verifying. 

I'm thinking it won't make a difference as the context determines which thread it should be confined to. In this case, we wouldn't need to point anything out in the docs.

**Comment by tonyarnold** [comment]
@jessesquires I think what you've proposed is a good approach. I don't think a callback on init is the answer. Thanks guys! Documentation issue, ahoy :)

**Comment by jessesquires** [comment]
Thanks for the feedback guys! :heart_eyes: 

By the way, I'm assuming you've found the `release-2.0` branch, but if not — now you know! This is a Swift 2.0/Xcode 7 branch, to be released when Swift/Xcode are final.

Also, while we are discussing this. I'm assuming you guys are actively using this library? If so, please keep feedback and PRs coming! :smile:

**Comment by tonyarnold** [comment]
@jessesquires I had found the branch, thanks! I'm not actively using it, but feeling like the time/effort I put into MagicalRecord could be minimised by switching to Swift. I've made a couple of attempts at starting, but they just end up looking like your library (with some MR-esque tweaks) so I think I'll just help you out :)

**Comment by jessesquires** [comment]
Hello all -- now on develop, `CoreDataStackFactory`. 

I hope to push `v2.0` this weekend.
