### ISSUE TITLE
OS X support

### ISSUE THREAD

**Issue by Bautastein** [jessesquires/JSQCoreDataKit#29]
My apologies if this question is at the wrong place. I'm new to GitHub. I watched your presentation at realm.io, and liked your clean approach. I tried to implement your solution with a designated Swift initializer in my OS X project which also uses bindings. When NSArrayController tries to make a new object of my NSManagedObject subclass, it crashes, because it tries to use init(entity:insertIntoManagedObjectContext:). That is an easy problem to fix, but when CoreData tries to open an existing archive from disk, it also tries to use the same initializer.

I tried, hackishly, to simply add init(entity:insertIntoManagedObjectContext:) as a convenience initializer, but this is far from ideal, because the ManagedObjectContext argument is optional, yet you need it to get an EntityDescription. The obvious solution was to try to use your CoreDataKit, so I tried to make a simple test project and use the Podfile. Cocoapods says:

[!] The platform of the target `Pods` (OS X 10.10) is not compatible with `JSQCoreDataKit (1.1.0)`, which does not support `osx`.

So I thought perhaps the designated initializer approach only works on iOS? Do you have plans to add support for OS X? I suppose that apart from the example project, very little should be different between the two platforms?

**Comment by jessesquires** [comment]
Thanks @Bautastein !

There's nothing in the framework that is iOS-specific. For the [2.0 release](https://github.com/jessesquires/JSQCoreDataKit/milestones) I'll update the pod spec to also support OS X.

**Comment by Bautastein** [comment]
Thank you. It seems to me, however, that the data models must contain an init(entity:insertIntoManagedObjectContext:) initializer. It might work on relaunch on iOS if the application is still in memory, but if the application must do a full restart and reload the data from persistent storage, it will fail without such an initializer. I am unfortunately not familiar with how these things on GitHub works, I haven't even used Git before. But I have made (uh... tried to make) a branch here:

https://github.com/Bautastein/JSQCoreDataKit/tree/persistence-unit-test

Is this link available to you? In JSQCoreDataTests/PersistenceTests.swift, there is a unit test which in my view should succeed. It fails with a fatal error if MyModel does not inherit init(entity:insertIntoManagedObjectContext:), but succeeds if it does.

**Comment by jessesquires** [comment]
So, because other parts of the CoreData framework rely heavily on KVO/KVC, implementing `init(entity:insertIntoManagedObjectContext:)` is necessary.

It will have to be another designated init (unfortunately), but I *think* you can make it `private` and `@objc`. This way, your Swift code will be required to use the full designated init, but CoreData can KVO/KVC via `init(entity:insertIntoManagedObjectContext:)`. For example, when executing a fetch request, CoreData would use this initializer behind the scenes.

**Comment by jessesquires** [comment]
Also, add platform badge to README: 

![Platform](https://cocoapod-badges.herokuapp.com/p/JSQCoreDataKit/badge.png)
