### ISSUE TITLE
CoreDataExtensions:fetch fails to compile in Swift 2.0

### ISSUE THREAD

**Issue by rlaurb** [jessesquires/JSQCoreDataKit#32]
The fetch method fails to compile because in Swift 2.0, NSManagedObjectContext.executeFetchRequest throws. I suggest something like the following:

    public func fetch <T: NSManagedObject>(request request: FetchRequest<T>, 
            inContext context: NSManagedObjectContext) -> FetchResult<T> {
        var results: [AnyObject]?
	var fetchResult = FetchResult<T>(success: false, objects: [], error: nil)
        context.performBlockAndWait { () -> Void in
		do {
			results = try context.executeFetchRequest(request)
			fetchResult.success = true
			fetchResult.objects = results as! [T]
		} catch let error as NSError {
			print("*** ERROR: [\(__LINE__)] \(__FUNCTION__) Error while executing fetch request: \(error)")
			fetchResult.error = error
		}
    }
	return fetchResult
}

**Comment by jessesquires** [comment]
Thanks @rlaurb ! :smile: 

This is already fixed on the `release-2.0` branch. Cocoapods will be updated soon!
