### ISSUE TITLE
Installing with Carthage, JSQCoreDataKit.framework ends up in the /Frameworks folder

### ISSUE THREAD

**Issue by nmelo** [jessesquires/JSQCoreDataKit#33]
I'm experiencing the following runtime error on XCode 7/iOS 9 (I'm on the `release-2.0` branch):

`dyld: Library not loaded: /JSQCoreDataKit.framework/JSQCoreDataKit
  Referenced from: /var/mobile/Containers/Bundle/Application/3803D54B-EB15-4759-8B9E-EE4D09B76855/MyApp.app/MyApp
  Reason: image not found
`

when installing JSQCoreDataKit with Carthage. 

I've added the .framework to `Linked Frameworks and Libraries`.

Creating a `Copy Files` step with Destination = "Products Directory" (with Code Sign on Copy) makes it run on the simulator, but still fails on the phone.

Any clues?

**Comment by jessesquires** [comment]
Hey @nmelo :smile: 

Sounds like either an issue with Carthage or your project setup.

Can you confirm if this issue occurs via other methods of linking the framework? (i.e., manually or via Cocoapods)
