### ISSUE TITLE
Function to reset stack / context

### ISSUE THREAD

**Issue by sverin** [jessesquires/JSQCoreDataKit#36]
I would like a function to reset the stack. Sometimes I remove to store (sqlite-file) and replace it with a backup and would like to reload the stack in an easy way.

**Comment by jessesquires** [comment]
Hey @sverin :smile: 

Why not initialize a new `CoreDataStack` object?

**Comment by jessesquires** [comment]
Oh, also -- `CoreDataModel` provides `removeExistingModelStore()`
