### ISSUE TITLE
UISearchController Behaviour

### ISSUE THREAD

**Issue by havocked** [jessesquires/JSQCoreDataKit#43]
Hi, 

First thanks for your library (and for your realm talk !)

Everything works fine but I'm struggling with this question : 
How I can adapt JSQCoreDataKit with a UISearchController the most swiftnessly possible.

Should I need to modify NSFetchedResultsController with a proper FetchRequest adapter everytime I select the UISearchController in my tableView ? Will it affect the delegate ?

Any thoughts on it would be greatly appreciated !

Anyway thanks again !

**Comment by jessesquires** [comment]
Hey @havocked :smile: 

What exactly do you mean? Can you describe this more? 

>Side note: If you need an easy setup for your FetchedResultsController's Delegate/DataSource, you should checkout my other library: https://github.com/jessesquires/JSQDataSourcesKit :smile:

**Comment by havocked** [comment]
<img width="242" alt="screen shot 2015-11-04 at 09 23 06" src="https://cloud.githubusercontent.com/assets/7999585/10933014/b171b5ec-82d5-11e5-8d52-de47e6d53c26.png">

So basically I'm trying to use a ```UISearchBar``` in my tableView

``` swift
 var resultSearchController: UISearchController?
```

I'm also using **JSQCoreDataKit** to fill the same tableView:

``` swift
let request = fetchAllCustomers(self.stack.mainContext)

self.frc = NSFetchedResultsController(fetchRequest: request, managedObjectContext: self.stack.mainContext, sectionNameKeyPath: nil, cacheName: nil)
self.frc?.delegate = self
        
fetchData()
```
``` swift
func fetchData() {
      do {
          try self.frc?.performFetch()
          tableView.reloadData()
      } catch {
          assertionFailure("Failed to fetch: \(error)")
      }
}
```
So that whenever I add quickly a new object in core data (new customer in this case) I only have to do this way :

``` swift
stack.mainContext.performBlockAndWait {
     Customer.newCustomer(self.stack.mainContext, firstName: firstName, lastName: lastName)
     saveContext(self.stack.mainContext)
}
```

Now my problem here is when I click on the search bar, How can I take advantage of JSQCoreDataKit and **directly make my request on Cora data** ? Or perhaps I **should copy the results in the tableView and apply a filter** ?

The last bit of information I have concerning this question is those two FetchRequest I return:

First one is the regular one, this is how I populate my TableView:
```swift
func fetchAllCustomers(context: NSManagedObjectContext) -> FetchRequest<Customer> {
     let e = entity(name: Customer.entityName, context: context)
     let fetch = FetchRequest<Customer>(entity: e)
     fetch.sortDescriptors = [NSSortDescriptor(key: "firstName", ascending: true)]
     return fetch
}
```

And the second one would be the one I'd like to use when I use the searchBar !
```swift 
func fetchCustomerForSearch(context: NSManagedObjectContext) -> FetchRequest<Customer> {
     let e = entity(name: Customer.entityName, context: context)
     let fetch = FetchRequest<Customer>(entity: e)
     fetch.sortDescriptors = [NSSortDescriptor(key: "firstName", ascending: true)]
     fetch.predicate = NSPredicate(format: "%K BEGINSWITH[cd] %@", "yolo") //whatever
     return fetch
}
```
Can I replace the ```self.frc``` by switching which request I want to select ?

Thank again for your *SWIFT* reply ! Big fan :+1:

**Comment by jessesquires** [comment]
Hm.. I think the common pattern here is to display a new view/controller specifically for your search results. This is what I would probably do.

With what you described, it sounds like you're trying to make this one view/controller do too much stuff.

**Comment by havocked** [comment]
Alright !

Will take to account your advice ! Thanks man !

**Comment by jessesquires** [comment]
:+1:

**Comment by jessesquires** [comment]
@havocked - Oh! Also, you should really check out https://github.com/jessesquires/JSQDataSourcesKit, too.

This library has components that encapsulate all of the boilerplate involved with `NSFetchedResultsController` and its delegate. There's a great demo project with examples.
