### ISSUE TITLE
Support For App Group

### ISSUE THREAD

**Issue by bassrock** [jessesquires/JSQCoreDataKit#45]
I think it would be a good improvement to support container url paths, for when sharing CoreData with a an AppGroup to be used in a TodayViewExtension.

**Comment by jessesquires** [comment]
Hey @bassrock :smile: 

This should be possible now. In CoreDataModel you can provide and bundle and file URL. 

Is there a limitation that you've found with this?

**Comment by bassrock** [comment]
Ah missed that thanks! Great work!
