### ISSUE TITLE
CoreData migrations: implement migration manager

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/JSQCoreDataKit#46]
The migration manager will be responsible for performing and managing migrations.

- Should be simple and only work with CoreData mapping models, iterating through them.
- Use `model.needsMigration` to detect if migrations are needed.

**Comment by 1791422018** [comment]
I am chinese,I come from china .I want to know how write a question in github.Can you help me?

**Comment by jessesquires** [comment]
Hey @1791422018 -- I don't understand. Do you want to open a new issue?

**Comment by 1791422018** [comment]
no no no ,I have a question ,but I don't know where I  can write in github

**Comment by jessesquires** [comment]
Hey @1791422018 - click "new issue"

**Comment by 1791422018** [comment]
ok,I see it,Thank you very much

**Comment by marius-serban** [comment]
Started doing some work on this one. Thinking about following the "Progressive Migrations" pattern defined [here](https://www.objc.io/issues/4-core-data/core-data-migration/).

**Comment by jessesquires** [comment]
@marius-serban Awesome! :tada: That's exactly want we want.

A few implementation notes:

- `CoreDataMigrationManager` should be a new object. `struct` if possible, **if** we need to save any state. **Otherwise**, a top-level `migrate()` function would be preferable.
- Inject all dependencies via `init` if using a new type, otherwise inject into the top-level function.

Please comment here with any questions, etc! :smile:
