### ISSUE TITLE
Carthage install error

### ISSUE THREAD

**Issue by devalfamac** [jessesquires/JSQCoreDataKit#48]
Following carthage error occurred while installation. Any suggestions?:

dev$ carthage update
*** Fetching JSQDataSourcesKit
*** Fetching JSQCoreDataKit
*** Checking out JSQCoreDataKit at "2.1.0"
*** Checking out JSQDataSourcesKit at "3.0.1"
*** xcodebuild output can be found in /var/folders/sg/vc3ry_wd77x_mv_qbdf0szf80000gr/T/carthage-xcodebuild.iagUVy.log
*** Building scheme "ExampleApp" in ExampleApp.xcodeproj
** BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
A shell task failed with exit code 65:
** BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)

**Comment by jessesquires** [comment]
Thanks @devalfamac !

**Comment by jessesquires** [comment]
Hey @devalfamac -- I just tested and `carthage build` ran fine for me using the [latest release](https://github.com/Carthage/Carthage/releases/tag/0.11) of Carthage and `JSQCoreDataKit`.

Can you provide any other information?

**Comment by devalfamac** [comment]
Thank you, with latest version of Carthage it works.
