### ISSUE TITLE
Resetting the stack

### ISSUE THREAD

**Issue by marius-serban** [jessesquires/JSQCoreDataKit#49]
Support for emptying all the managed object contexts in the stack and clearing the persistent store.

**Comment by jessesquires** [comment]
Hey @marius-serban :smile: 

To do this you can:

1. Destroy and re-create your `CoreDataStack`
2. Then [remove the existing model store](http://www.jessesquires.com/JSQCoreDataKit/Structs/CoreDataModel.html#/s:FV14JSQCoreDataKit13CoreDataModel24removeExistingModelStoreFS0_FzT_T_) from disk with `model.removeExistingModelStore()`

**Comment by marius-serban** [comment]
Hey @jessesquires , Isn't the right order of operations the following?
1. [Remove the existing model store](http://www.jessesquires.com/JSQCoreDataKit/Structs/CoreDataModel.html#/s:FV14JSQCoreDataKit13CoreDataModel24removeExistingModelStoreFS0_FzT_T_) from disk with `model.removeExistingModelStore()`
2. Re-create the `CoreDataStack`

**Comment by marius-serban** [comment]
One might want to safely reset an *existing* instance of `CoreDataStack`. Many people I suspect, will have their `CoreDataStack` instance distributed trough the view controller hierarchy. Resetting it trough re-creation would require updating the references in all those view controllers which is inconvenient.

I'll gladly contribute towards this feature if you are willing to admit it in the project.

**Comment by jessesquires** [comment]
> Isn't the right order of operations the following?

Ah, yes :smile:
