### ISSUE TITLE
Update .travis.yml when travis-ci supports Xcode 6.3

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/JSQCoreDataKit#5]
Also update `README` with travis-ci badge.

[![Build Status](https://secure.travis-ci.org/jessesquires/JSQCoreDataKit.svg)](http://travis-ci.org/jessesquires/JSQCoreDataKit)

**Comment by jessesquires** [comment]
From travis-ci:
http://blog.travis-ci.com/2015-04-20-state-of-the-mac-infrastructure-on-travis-ci/

**Comment by tonyarnold** [comment]
You could consider switching to CircleCI, which already supports Xcode 6.3.x (and has done so for a while now). I've used it on a few projects, and it works well. Happy to submit a PR if you're keen.

**Comment by jessesquires** [comment]
Hey @tonyarnold - thanks for the suggestion!

I'm already pretty heavily invested in travis. All of my projects use it, CocoaDocs integrates with it, etc. They seem to be working on a solution to iterate more quickly on OS X and iOS, so i'm hoping this will surface soon and address future issues. Also, it's really nice that travis is free for open-source — it doesn't look like CircleCI does that.

**Comment by nanoxd** [comment]
This should be possible now

**Comment by jessesquires** [comment]
thanks @nanoxd !
