### ISSUE TITLE
Reset stack on background queue, add completion closure to `resetStack` function

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/JSQCoreDataKit#51]
Follow this pattern:
https://github.com/jessesquires/JSQCoreDataKit/blob/develop/JSQCoreDataKit/JSQCoreDataKit/CoreDataStackFactory.swift#L86-L88

**Comment by jessesquires** [comment]
/cc: @marius-serban — Let me know if you'd like to work on this. No worries if not, I was going to do it today but didn't have time. Just wanted to ask! :smile:

**Comment by marius-serban** [comment]
+1 I'd be happy to
