### ISSUE TITLE
Have tvOS CoreDataModel init's storeType default to CachesDirectory URL

### ISSUE THREAD

**Issue by cgoldsby** [jessesquires/JSQCoreDataKit#61]
`CoreDataModel` init method storeType defaults to a SQLite DB using the Documents Directory URL: `storeType: StoreType = .SQLite(DocumentsDirectoryURL())` 

On tvOS, the Document Directory is not available and it would be a nice enhancement to have the init method default to the Caches Directory.

A proposal would be to refactor `DocumentsDirectoryURL()` to `DirectoryURL()` and add an availability check when creating the directory URL: 
```
var searchPathDirectory = .DocumentDirectory
#if os(tvOS)
    searchPathDirectory = .CachesDirectory
#endif
return try NSFileManager.defaultManager().URLForDirectory(searchPathDirectory, ...)
```

**Comment by jessesquires** [comment]
Hey @cgoldsby ! :smile: 

Sounds like a great idea. Would you like to submit a pull request?

If so, let's call it `DefaultDirectoryURL()`.

**Comment by cgoldsby** [comment]
Will do.
