### ISSUE TITLE
Default saving uses performBlockAndWait and leads to deadlock?

### ISSUE THREAD

**Issue by amitai-hoze** [jessesquires/JSQCoreDataKit#68]
## General information

- Library version(s): 2.2.0

## Description

Hi, we're using your excellent framework, and I noticed that the saving performed on `didReceiveChildContextDidSaveNotification` is using `performBlockAndWait` by default (see [here](https://github.com/jessesquires/JSQCoreDataKit/blob/67f2e02ab257aba83286ddcb635222c4b4a71813/JSQCoreDataKit/JSQCoreDataKit/CoreDataStack.swift#L145)).

This may cause deadlocks, for example, if I replace the implementation of [`didTapAddButton`](https://github.com/jessesquires/JSQCoreDataKit/blob/67f2e02ab257aba83286ddcb635222c4b4a71813/ExampleApp/ExampleApp/CompanyViewController.swift#L119) in the `ExampleApp` with:

``` swift
    func didTapAddButton(sender: UIBarButtonItem) {
        let childContext = stack.childContext()
        childContext.performBlock {
            Company.newCompany(childContext)
            saveContext(childContext, wait: false)
        }
        
        for i in 1...10 {
            childContext.performBlockAndWait { }
            print(i)
        }
    }
```

It deadlocks.. I iterate 10 times just to make sure, but it deadlocks on the 2nd time.

The problem is that there's an implicit waiting when using `saveContext(childContext, wait: false)`, i.e. the `childContext` thread is waiting for the `mainContext` to save..

Why not use a different mechanism for the parent's context saving, so that the waiting behaviour will be preserved?

Thanks in advance, Amitai.

**Comment by jessesquires** [comment]
Thanks @amitai-hoze ! :smile: 

Sounds like `saveContext(context, wait: false)` would fix the issue, correct? 

Would you like to submit a pull request?

**Comment by jessesquires** [comment]
Hey @amitai-hoze :smile: 

I investigated this more, and here's what I found:

According to [the docs](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/CoreDataFramework/Classes/NSManagedObjectContext_Class/#//apple_ref/occ/instm/NSManagedObjectContext/performBlockAndWait:):

>`func performBlockAndWait(_ block: () -> Void)`
>
> **This method may safely be called reentrantly.**

This note is not present for `performBlock:`, meaning it is **not** [reentrant](https://en.wikipedia.org/wiki/Reentrancy_%28computing%29).

Your code snippet here is the issue, not the library. You're misusing CoreData.

Here's the correct want to achieve this:

```swift
    func didTapAddButton(sender: UIBarButtonItem) {
        let childContext = stack.childContext()
        childContext.performBlock {
            Company.newCompany(childContext)

            saveContext(childContext, wait: false, completion: { (result) in
                for i in 1...10 {
                    childContext.performBlockAndWait { }
                    print(i)
                }
            })
        }
    }
```

If `wait == false`, and you need to perform other operations when the save is finished, you'll need to use the `completion` closure.

Hope this helps! :blush:

**Comment by amitai-hoze** [comment]
Hi, thanks for you reply :smile:

I'm not sure why you referred to `performBlock` not being reentrant.. AFAIK, reentrancy is only relevant when using `performBlockAndWait`.
It means that e.g. this code:
``` swift
context.performBlockAndWait {
  
  // do some operations
  context.performBlockAndWait {
    // do some more..
  }
}
```
will not deadlock. When using `performBlock` reentrantly, there is no chance for deadlocking, since it is all async:

``` swift
context.performBlock {
  
  // do some operations
  context.performBlock {
    // do some more..
  }
}
```
Also, the only place I used `performBlock` reentrantly , is when invoking `saveContext(childContext, wait: false)` inside the block, but your solution does the same..

The reason it deadlocks according to my research, is that `saveContext(childContext, wait: false)` calls a `context.save()` inside its block, and that calls `didReceiveChildContextDidSaveNotification(notification:)` **synchronously**, which then calls the child context's parent (the main context) `performBlockAndWait` to save it, meaning the `childContext`'s thread is now **blocked and waiting** for the main thread to perform that block.

The problem arises when we call `childContext.performBlockAndWait` from the main thread.. The main thread is waiting for the `childContext`, but the block running on the `childContext`'s queue is waiting for the main thread to do its `performBlockAndWait`, hence, a deadlock.

The initial code I sent was just to illustrate a problem.. The loop that iterates 10 times was intended to simulate a user action (e.g.), that also uses that `childContext` in order to do some actions in the background. I did it 10 times in order to "catch" the other block in the `childContext`'s queue while it waits for the main thread, so that the deadlock could be reproduced.

Actually, using core data with `performBlockAndWait` in conjunction with other threading mechanisms is known to cause deadlocks, and it is one's responsibility to use it safely, but here there is a hidden `performBlockAndWait` on the parent context every time we save a context, and it may go unnoticed, thus creating deadlocks.

**Comment by jessesquires** [comment]
Ahh, interesting. Thanks for the clearer explanation @amitai-hoze ! :smile: 

What's your proposed solution? :sweat_smile:

**Comment by amitai-hoze** [comment]
Hi, researched it a little more and it turns out the deadlock is actually caused by Core Data normal behavior..

Even when I changed the notification observer's behavior to `saveContext(context, wait: false)` my example still deadlocks.
It seems that saving a `childContext` waits for its parent context's thread **anyway** before it saves. I didn't find anything conclusive in the documentation, but it seems that this is the behavior.

This means that once you perform `childContext.save()` anywhere in your code, you can't use `childContext.performBlockAndWait` safely anymore.

Although this is not directly related to you framework, it might be a gotcha for users. Maybe add something to the documentation. Also, while researching this I came across [Core Data: parent context blocks child's answer](http://stackoverflow.com/a/29918585/1346426), which may explain the locking behavior. What are your thoughts about his objection for using parent-child contexts for background operations?

**Comment by jessesquires** [comment]
Ah, yep. :smile: Actually, I know Daniel Eggert and spoke with him about CoreData recently.

See #60. Looks like this issue should take care of everything.

Thanks so much for the investigations @amitai-hoze! I really appreciate it! Please keep contributing. :blush: 

Going to close out this issue.

**Comment by amitai-hoze** [comment]
Great, thanks :smile:
