### ISSUE TITLE
Add extensions to replace free functions

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/JSQCoreDataKit#69]
>Prefer methods and properties to free functions.
>
> [Swift API Design Guidelines](http://apple.github.io/swift-internals/api-design-guidelines/)

~~Let's keep the free functions in place, but add extensions to types (which should call the free functions).~~

**Update:***

- [x] extension on `NSManagedObjectContext` for delete
- [x] extension on `NSManagedObjectContext` for fetch
- [x] move `resetStack` to `CoreDataStack`

**Comment by jessesquires** [comment]
If submitting a pull request, please do 1 function at a time. (1 per PR) 😄

**Comment by Liquidsoul** [comment]
> ~~Let's keep the free functions in place, but add extensions to types (which should call the free functions).~~

If the objective is to keep the free functions for background compatibility, maybe it's the free functions that should call the extensions methods 🤔

And do you want the implementation of the library to still use the free function or the extension methods?

**Comment by jessesquires** [comment]
Hey @Liquidsoul 

> If the objective is to keep the free functions for background compatibility....

Yes, originally the goal was to make this change backward compatible, but I've decided against that since #60 has been completed — which is a breaking change. 😄 

So, this task is set for the `4.0.0` release too, which will be breaking (from the current `3.0.0`).

>And do you want the implementation of the library to still use the free function or the extension methods?

I think it would be best to have 1 way to do things. For example:

```swift
// OLD - remove this
saveContext(context)

// NEW - add this
context.save()
```

So we'll remove the free functions and replace them with extensions.

**Comment by jessesquires** [comment]
Here's what I'm thinking:

- extension on `NSManagedObjectContext`
    - save
    - fetch
    - delete
- move `resetStack` to `CoreDataStackFactory`
- let's leave `entity()` alone for now

😄

**Comment by Liquidsoul** [comment]
👍 for 1 PR for each.
I do not know if it will be possible to extend `NSManagedObjectContext` with a custom `save()` because `save() throws` already exist on the object and we're using it in `saveContext()` 😅 
It will be interesting to look into this 😁

**Comment by Liquidsoul** [comment]
Where do you want the extensions to be?
`CoreDataFunctions.swift` does not fit anymore.
What do you think of using a file named `NSManagedObjectContext+JSQCoreDataKit.swift`?
Maybe we can find an better name that `+JSQCoreDataKit` but I cannot come up with something else right now 🤔

> * let's leave entity() alone for now

Damn! That was the first I did yesterday evening 😅 I'll keep it for later then 😉

**Comment by jessesquires** [comment]
>I do not know if it will be possible to extend `NSManagedObjectContext` with a custom `save()` because `save()` throws already exist

Haha. Derp. I wasn't thinking. I suppose let's leave `saveContext()` as-is for now. 😊 

>Where do you want the extensions to be?

How about, `CoreDataExtensions.swift` ? 😄 

>Damn! That was the first I did yesterday evening

Ha. Where did you put this? I guess on `NSEntityDescription` ? You know what, `entity()` may not be necessary with Swift 3.0 and the "Great API Transformation". Let's hold off for now and see what happens in Swift 3.

**Comment by Liquidsoul** [comment]
> How about, `CoreDataExtensions.swift` ? 😄

👍 

> Ha. Where did you put this? I guess on `NSEntityDescription` ?

Yup 😉 

> You know what, `entity()` may not be necessary with Swift 3.0 and the "Great API Transformation". Let's hold off for now and see what happens in Swift 3.

Let's leave it alone then 😃

**Comment by Liquidsoul** [comment]
I've just submitted the last modification for the `fetch` function here #78.
As I told you, I already did the `entity` one. You can see the modification there a19ca1e3f6ec8a5266cd83eab9b9d14b79456ef2 and if you change your mind about integrating the change, I can create a pull request 😉

**Comment by jessesquires** [comment]
Closing. Complete as of 	2683bdb.

**Comment by jessesquires** [comment]
@Liquidsoul 

FYI, see #87
