### ISSUE TITLE
Nested context decision

### ISSUE THREAD

**Issue by piercifani** [jessesquires/JSQCoreDataKit#71]
This is more a question then an issue, but: why do you set the `backgroundContext` as the `mainContext`'s parent? This seems unnecessary since you still have to merge the changes through the `NSManagedObjectContextDidSaveNotification`

In my tests, connecting the `mainContext` directly to the `persistentStoreCoordinator` makes all the tests pass (except the one that tests that the `mainContext` has a `parentContext`, off course). 

Would you be willing to make these changes if a performance tests (that I would make, off course) wield better results?

**Comment by jessesquires** [comment]
Haha, way ahead of you: #60 😉 

Thanks @piercifani 👍
