### ISSUE TITLE
Add OS X test target

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/JSQCoreDataKit#79]

**Comment by Liquidsoul** [comment]
I saw that the project App has a dedicated scheme for testing. I think it is possible to have each target scheme to have their testing setup.
I could look into that 😃

**Comment by jessesquires** [comment]
hey @Liquidsoul ! i've got some progress here locally already 👍 

i'll push this within the next couple days 😊

**Comment by jessesquires** [comment]
done in dd0dabb4135f604ae8919c5c4da7d40e6738a660
