### ISSUE TITLE
removeExistingStore not removing associated .sqlite-shm and .sqlite-wal files

### ISSUE THREAD

**Issue by deemadden** [jessesquires/JSQCoreDataKit#85]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/jessesquires/JSQCoreDataKit/blob/develop/README.md) and [documentation](http://www.jessesquires.com/JSQCoreDataKit/).
- [x] I have reviewed the [contributing guidelines](https://github.com/jessesquires/HowToContribute).
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQCoreDataKit/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- Library version(s): 4.0.1
- OS version(s): 9.3.1
- Devices/Simulators affected: I've only tried it on a 6s and 6s Plus
- Reproducible in the demo project (Yes/No): Yes
- Related issues: Affects creating a stack from the CoreDataStackFactory using createStack()

## Expected behavior

> Should be able to rebuild an empty model and create a stack by calling createStack() after calling removeExistingStore on CoreDataModel

## Actual behavior

> Fails, throwing a bunch of model errors (see below).  I was able to resolve the issue by deleting the model's associated .sqlite-shm an .sqlite-wal files (these are files auto generated at sqlite db creation time in newer versions of iOS)

I was able to determine that deleting the .sqlite-shm and .sqlite-wal files - which live in /Documents, right next to the .sqlite database - fixed the problem.

## Steps to reproduce

> Call removeExistingStore on your current core data model, attempt to rebuild somewhere thereafter by rebuilding your core data stack using CoreDataStackFactory's createStack()

### Crash log? Screenshots? Videos? Sample project?

> Error as it appears in the console:
`CoreData: error: (522) I/O error for database at [path to sqlite db].  SQLite error code:522, 'not an error'
2016-06-04 15:12:58.537 Golf[6313:1458291] CoreData: error: -addPersistentStoreWithType:SQLite configuration:(null) URL:file:///[path to sqlite db] options:{
    NSInferMappingModelAutomaticallyOption = 1;
    NSMigratePersistentStoresAutomaticallyOption = 1;
} ... returned error Error Domain=NSCocoaErrorDomain Code=522 "(null)" UserInfo={NSSQLiteErrorDomain=522, NSUnderlyingException=I/O error for database at [path to sqlite db].  SQLite error code:522, 'not an error'} with userInfo dictionary {
    NSSQLiteErrorDomain = 522;
    NSUnderlyingException = "I/O error for database at [path to sqlite db].  SQLite error code:522, 'not an error'";
}`

**Comment by jessesquires** [comment]
Thanks so much @deemadden ! 👍 

I'll get this fixed soon, and release 4.0.2 — unless you want to submit a PR.

**Comment by deemadden** [comment]
Sure @jessesquires I pretty much have the fix written. I can find the spot to put it and submit one.

**Comment by jessesquires** [comment]
Notes on sqlite temp files:
https://www.sqlite.org/tempfiles.html

**Comment by deemadden** [comment]
Thanks @jessesquires
