### ISSUE TITLE
Rename `stack.managedObjectContext` to `stack.context`

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/JSQCoreDataKit#9]
This feels/reads better.

Update docs and README for changes.

**Comment by tonyarnold** [comment]
What about `persistentStoreCoordinator`? Seems like it would be a likely candidate for shortening down to `storeCoordinator` or similar.

**Comment by jessesquires** [comment]
I think that sounds good, too.

My thoughts here were that you'd be accessing `stack.context` **much** more often than `stack. persistentStoreCoordinator `
