### ISSUE TITLE
Podspec needs to specify Swift version 3.0

### ISSUE THREAD

**Issue by oliverfoggin** [jessesquires/JSQCoreDataKit#98]
## New issue checklist

- [x] I have read the [`README`](https://github.com/jessesquires/JSQCoreDataKit/blob/develop/README.md) and [docs](http://www.jessesquires.com/JSQCoreDataKit/).
- [x] I have reviewed the [contributing guidelines](https://github.com/jessesquires/HowToContribute).
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQCoreDataKit/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- Library version(s): 6.0.0
- OS version(s): MacOS 10.12
- Devices/Simulators affected: No
- Reproducible in the demo project (Yes/No): No
- Related issues: None

## Expected behavior
- No "Convert to Current Swift Syntax" dialog should appear after installing cocoapod
- Project should build

## Actual behavior
- "Convert to Current Swift Syntax" dialog appears after installing cocoapod
- Project does not build. Error that JSQCoreDataKit is using legacy Swift.

## Steps to reproduce
Create a project using Swift 3.
Install latest cocoapod 6.0.0
Open project workspace
Dialog opens to ask to "Convert to Current Swift Syntax"

### Crash log? Screenshots? Videos? Sample project?
![screen shot 2016-10-13 at 11 18 58](https://cloud.githubusercontent.com/assets/1813244/19345600/f027e32c-9136-11e6-9e43-5b8992a20618.png)

This can be fixed by adding...

    "pod_target_xcconfig": { "SWIFT_VERSION": "3.0" }

to the podspec but I don't know the syntax of the podspec file that you are using. I am used to the old  syntax so not sure how it works with your podspec.

Once this is added to the podspec it should quiet the dialog.

**Comment by oliverfoggin** [comment]
OK, the required syntax is...

    s.pod_target_xcconfig =  { 'SWIFT_VERSION' => '3.0' }

**Comment by DenHeadless** [comment]
I believe what you should do instead, is use latest CocoaPods(1.1.0.rc.3) and create .swift-version file in root of your project, specifying 3.0 inside.

Or, as a workaround(with CocoaPods 1.0.0), you can run post install hook like so:

```swift
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
```

Reason is, when for example Swift 3.0.1 or Swift 3.1.0 gets released, even if there will be no source changes required for the library, podspec can immediately broke, since Xcode setting may change. At least that's my thought process as library author myself =)

**Comment by oliverfoggin** [comment]
@DenHeadless ah, ok. I didn't know that.

I will give that a try.

I was purely going on how other frameworks have solved this problem.

Thanks

**Comment by jessesquires** [comment]
Thanks @DenHeadless ! 👍 

We do have a `.swift-version` file: https://github.com/jessesquires/JSQCoreDataKit/blob/develop/.swift-version

So is this project setup correctly? Or do we need to update the spec?

**Comment by jessesquires** [comment]
Looks like Orta has confirmed:

https://twitter.com/orta/status/786599214138716160

**Comment by oliverfoggin** [comment]
So, is this documented anywhere? How did you find how to fix this using the .swift-version file and updating to rc3?

I can't find anything that references this.
